language: php
dist: trusty

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 
